### ISSUE TITLE
Application not launch

### ISSUE THREAD

**Issue by Paul75** [achunt2143/W-Launcher#10]
Hello

The application not start it crash ans close .

I use Huawei Mate 40 pro. 

Thanks

**Comment by achunt2143** [comment]
Hi thank you. I noticed that too, it did not occur during my initial testing. Can you describe what you were doing before the crash?

**Comment by Paul75** [comment]
Hello,

When I launch it not start and en bottom tell me that can't start ....

Thanks

**Comment by achunt2143** [comment]
Thank you. Did you by chance have the 'System' theme applied? I found a bug with that which was causing the app to not start. It should be resolved now with version 2.3.2. Please check it out and let me know if it resolves the issue.

**Comment by Paul75** [comment]
On last github version works. Not with fdroid version

**Comment by achunt2143** [comment]
Okay great. I don't really know how the fdroid is handled, but I'm sure it will be updated soon. Thanks again for bringing this up!
