### ISSUE TITLE
Messaging app icon doesn't do anything

### ISSUE THREAD

**Issue by NuclearKev** [achunt2143/W-Launcher#14]
On Pixel 4a Android 13 when I press the messaging icon nothing happens. I have my default SMS app set.

Any ideas what might be causing this?

**Comment by achunt2143** [comment]
Will look into this in the next few days including your other issues. I tested myself and can't reproduce what you are seeing so might need some more details from you. Will post back!

**Comment by NuclearKev** [comment]
Hi @achunt2143, I actually figured out the issue with a few of the problems. It's because I'm using /e/OS and there is no `com.android.messages` app. I changed it to the one that exists on my system and it's working well.

**Comment by achunt2143** [comment]
Good to know! I do plan on correcting that if I can to be dynamic and let the user choose the right apps.
