### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [achunt2143/W-Launcher#2]
Just wondering what license this app falls under, could you please clarify? I've searched the repo and found references to Apache-2 as well as GPL-3, so I assume as that's used by components, the resulting app will be GPL-3.0?

**Comment by achunt2143** [comment]
> Just wondering what license this app falls under, could you please clarify? I've searched the repo and found references to Apache-2 as well as GPL-3, so I assume as that's used by components, the resulting app will be GPL-3.0?

Yes that is correct. It is under GPL-3 license.

**Comment by IzzySoft** [comment]
Thanks! Maybe you could make that obvious by placing the corresponding `LICENSE.txt` in the project root (Github then automatically detects it), or at least mention it in the Readme? Afraid not everyone takes the time to dig into the issues :wink:

One more thing: All APKs identify as

    package: name='com.achunt.weboslauncher' versionCode='1' versionName='1.0'

Would be great if you could [fix it here](https://github.com/achunt2143/W-Launcher/blob/main/app/build.gradle#L12). Especially important is to increase `versionCode` with each release, as that's what Android uses to tell versions apart. `versionName` is for humans to read, so for the currently latest tag it is matching (but not for all the others). Seeing this is already the 21st release:

```gradle
        versionCode 21
        versionName "1.0"
```

would have been fine.

**Comment by achunt2143** [comment]
> Thanks! Maybe you could make that obvious by placing the corresponding `LICENSE.txt` in the project root (Github then automatically detects it), or at least mention it in the Readme? Afraid not everyone takes the time to dig into the issues :wink:
> 
> One more thing: All APKs identify as
> 
>     package: name='com.achunt.weboslauncher' versionCode='1' versionName='1.0'
> 
> Would be great if you could [fix it here](https://github.com/achunt2143/W-Launcher/blob/main/app/build.gradle#L12). Especially important is to increase `versionCode` with each release, as that's what Android uses to tell versions apart. `versionName` is for humans to read, so for the currently latest tag it is matching (but not for all the others). Seeing this is already the 21st release:
> 
> ```gradle
>         versionCode 21
>         versionName "1.0"
> ```
> 
> would have been fine.

Thanks for your suggestions! I'll definitely be adding the license in github and in the application. This is the first project I've done that uses components that requires this license, so I'm figuring things out as we go. As for the version number and code, I found out about that today and will be updating that accordingly. I will be updating it appropriately with the next release.

**Comment by IzzySoft** [comment]
Thanks! Then I stand prepared. With the next sync at around 7 pm UTC, *W Launcher* will [show up in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.achunt.weboslauncher). If you wish I can send you the metadata I prepared for that via PR in [Fastlane format](https://gitlab.com/-/snippets/1895688) so you can adjust it to your likings; changes will then automatically be pulled along with new releases.

Oh, while setting it up my framework also pulled your `FUNDING.yml`. I wondered about the weird donation link created and see [there's an error here](https://github.com/achunt2143/W-Launcher/blob/main/.github/FUNDING.yml#L4): `custom:` requires a full URL, i.e. starting with `https://`, not just `domain/page` (which is why Github shows it as `http://` instead of `https://`), so that line should read

```yaml
custom: ['https://paypal.me/achunt2143']
```

I've fixed that in my local copy for now. As thus it has a newer timestamp than yours a new copy will only be fetched after your next edit, so please make sure to adjust this then as well. Up to 4 custom URLs (comma separated) can be in that field, so if you have more, just add them as well :wink:

```yaml
custom: ['https://paypal.me/achunt2143','https:/ko.fi/achunt2143']
```

**Comment by achunt2143** [comment]
Thanks! Yeah, if you could send that over, that would be great. And thanks for the tip on the donation link! I just copied it from PayPal, but I'll make sure it's updated correctly 🙂

**Comment by IzzySoft** [comment]
> if you could send that over, that would be great

On its way!

> I'll make sure it's updated correctly

:star_struck: Thanks!

**Comment by achunt2143** [comment]
Updating everything now! Sorry for the delay.

**Comment by IzzySoft** [comment]
No worries, it's a hobby and not a hunt :wink:

**Comment by achunt2143** [comment]
That's right! If all is good, I think we can close this one out. :)

**Comment by IzzySoft** [comment]
Yes, indeed we can! Thanks for your help!
