### ISSUE TITLE
[Feature Request] ios-style

### ISSUE THREAD

**Issue by Pantyhose-X** [achunt2143/W-Launcher#5]
**Is your feature request related to a problem? Please describe.**
All your apps will be shown on the Home screen.

**Describe the solution you'd like**

Show all apps on home screen
**Additional context**
![Screenshot_20210427-093745](https://user-images.githubusercontent.com/42504385/116172999-df004280-a75f-11eb-8048-50c44f2308ca.jpg)

**Comment by achunt2143** [comment]
Thanks for the suggestion, but as the inspiration for the launcher was not to do this, this will not be added as a feature.
