### ISSUE TITLE
Work Profile apps not showing, new app installs not showing unless clearing app storage

### ISSUE THREAD

**Issue by ghost** [achunt2143/W-Launcher#6]
**Description:**
I am using the launcher on my Fairphone 4 running CalyxOS with Android 13. I see an issue where my Work Profile apps are not showing up in the launcher. Additionally, new app installs are also not showing up unless I clear the app storage.

**Steps to Reproduce:**
Install W-Launcher and open it on any android phone I asume.
Install any app within the work profile.
Launch W-Launcher and observe that Work Profile apps are not visible.

Also Installing any new app and observe that it does not appear in the launcher until app storage is cleared.

**Expected behavior:**
All apps installed within the Work Profile should be visible in the launcher.
New app installs should appear in the launcher without needing to clear app storage.

**Actual behavior:**
Work Profile apps are not visible in the launcher, and new app installs do not appear in the launcher until app storage is cleared.

**Another Note:**
Hiding the App Icon for the W-Launcher in the W-Launcher app drawer.

**Device info:**

OS: CalyxOS
Android: 13
Phone: Fairphone 4

Thanks for looking into this issue.

**Comment by achunt2143** [comment]
Thank you so much for bringing this to my attention. I think I have an idea about what is causing the delay in uninstalled apps still showing, so I will get working on that.

For Work Profile, I do not understand what you mean? Do you mean apps that are controlled by an organization? I do not have an issue with those not showing up. Can you elaborate more on what Work Profile is?

**Comment by midtsveen** [comment]
Sure!
In CalyxOS, Work Profile is a feature that allows you to create a separate, offline, secure workspace on your device.

But It's commonly used on stock android to separate work-related apps and data from personal apps and data. Work Profile essentially creates a new profile on your device that's managed separately from your main profile.

This means that any apps or data that you install or create within your Work Profile are kept separate from your personal apps and data. So if you have apps that you only want to use for work or that are managed by an organization, you can keep them separate using the Work Profile feature.

![Screenshot_20230324-234803](https://user-images.githubusercontent.com/105129613/227657070-7a385709-00a8-4adc-b651-773aa9f84a66.png)

**Comment by achunt2143** [comment]
Thank you so much! It's great to hear that this little side project I started is being used and enjoyed by users. I appreciate all your feedback given! 2.1 release should be out in a few hours on play store!

**Comment by midtsveen** [comment]
That's great to hear! Keep up the research and don't worry if you can't find specific code resources for the work profile app issue in the end.

**Comment by achunt2143** [comment]
I think I found something. It seems like it works, but I don't have any work profile apps like yours I can try. Check out version 2.2.2 and see if that does anything different. It should put the work apps on a new tab titled "Work"

**Comment by midtsveen** [comment]
Thank you for working on this issue. I will download the latest version of the launcher and test to confirm if it resolves the problem with work profile apps not showing up.

**Comment by achunt2143** [comment]
closing due to requestor deleting profile
