### ISSUE TITLE
Incorporate Material You into theme that follows system icon theme <3

### ISSUE THREAD

**Issue by midtsveen** [achunt2143/W-Launcher#7]
Hi there,

I would like to request a new addon for the option in the launcher theme setting called **system**. Currently, the theme has an option to follow the **system** icon theme, which is a great feature. However, I think it would be even better if the theme could incorporate Material You, the new design language from Google that was introduced in Android 12.

Material You is a visually appealing and modern design language that would make the launcher theme even more attractive and user-friendly. By incorporating Material You, the launcher theme would be able to keep up with the latest design trends and offer a more cohesive experience for users who are already using Material You on their devices.

I understand that this may not meet the launchers WebOS look, but I believe it would be a great addition to the launcher theme. 

Screenshot:
![Screenshot_20230324-204149](https://user-images.githubusercontent.com/105129613/227624075-9db53b2c-4586-4e82-a133-6076865e453a.png)

**Comment by achunt2143** [comment]
This is great! I'll need to look at the Material You specifications and get working on this. I'm adding this to the TODO list for sure!
